### ISSUE TITLE
Script Compilation Defines appear to have stopped working

### ISSUE THREAD

**Issue by XaeroDegreaz** [Chaser324/unity-build#12]
I'm not sure what happened, but I removed a script compilation define from one of the builds, and now no custom defines are coming through when building.

Any ideas on how to debug?

I've clicked the "Refresh BuildConstants and Apply Defines" button and that appears to apply the script defines for that one selected project as the defaults in the build settings, which is not what I want I think.

Thanks in advance

**Comment by Chaser324** [comment]
Did you pull the most recent code? I think I just fixed this issue, but I guess it's possible it's still broken.

**Comment by XaeroDegreaz** [comment]
Wow, talk about response speed!

Nope I haven't pulled since I last talked to you. Let me do that and I'll get back to you.

**Comment by Chaser324** [comment]
Yeah. Not sure when I broke it, but I just committed what I think is a fix a day or two ago.

**Comment by XaeroDegreaz** [comment]
Yeah that's crazy that I just noticed it (seems we both noticed it around the same time). It seemed to always work before, but I think I may have actually had one of the defines in the global settings before which may be why I never actually noticed haha, woops.

Anyhow, that totally fixed it.

I did notice that the default settings that are in the build settings don't get set back to their original content. This may not be a big deal for people who use SuperUnityBuild for every build they do, but for some people who do one-off builds using the default built-in mechanism without really thinking about it may find themselves banging their heads against the walls. For me, I use your product for every build so I don't see it being much of a bother to me.

That and it alters the `ProjectSettings.asset` which may prove to be a little annoying to commit and pass around on teams with more than a couple people.

Perhaps adding an option to "Set scripting defines back to original values after build" would be great for them. Probably have to add a warning that it will cause a longer build time as Unity has to basically recompile everything once you switch defines again.

**Comment by Chaser324** [comment]
Yeah, you're totally right about that. Hadn't thought about it before, but it definitely should make sure that it saves that state before a build and restores it after so that nothing actually changes from the perspective of working in the editor. I'll make a separate issue to remind me.

I'm going to consider this issue closed since it sounds like that most recent commit fixed it for you.
