### ISSUE TITLE
Improve SceneListDrawer performance.

### ISSUE THREAD

**Issue by Chaser324** [Chaser324/unity-build#20]
As noted in PR #18 and #19, SceneListDrawer causes significant performance issues on large projects.

**Comment by DomDomHaas** [comment]
Okay thx :)

**Comment by Chaser324** [comment]
After some consideration, I think I'm just going to get rid of the drop down list of scenes altogether and try to move to a drag and drop system. That should get rid of the performance issue and shouldn't really be all that much of an inconvenience for anyone considering that's how the standard Unity build settings window works.

**Comment by Chaser324** [comment]
Addressed by commit 758692ffc12dc07e691643a77ab32caf04471d39. There's still room for improvement, but it is now at least possible to work with 500+ scene projects without losing your mind.
