### ISSUE TITLE
Plugin does not appear in Top Bar in 2017.2.0f3

### ISSUE THREAD

**Issue by professionaljones** [Chaser324/unity-build#23]
Unlike previous versions, the controls for the plugin are accessible once the user selects it from the Window Tab.

using Unity 2017.2.0f3 on Windows 10

**Comment by Chaser324** [comment]
This was an attempt to abide a bit more to the Unity Asset Store submission guidelines in case I submit this at some point. I may be able to compromise a bit between the two approaches.
