### ISSUE TITLE
Support for Unity 2017.3

### ISSUE THREAD

**Issue by Arugin** [Chaser324/unity-build#25]
There are a lot of warnings right now:

    warning CS0618: `UnityEditor.BuildTarget.StandaloneOSXIntel' is obsolete: `StandaloneOSXIntel has been removed in 2017.3'
    warning CS0618: `UnityEditor.BuildTarget.StandaloneOSXIntel64' is obsolete: `StandaloneOSXIntel64 has been removed in 2017.3'

etc.

**Comment by Chaser324** [comment]
I haven't had an opportunity to download and take a look at 2017.3, but I'll address these as soon as I can.

**Comment by Chaser324** [comment]
Closed by f2472758acba5d59b4ac81088b4cca529670b8b4
