### ISSUE TITLE
Execute unit tests (Unity Test Tools) before building. If a test fails, abort build process.

### ISSUE THREAD

**Issue by sampaiodias** [Chaser324/unity-build#28]

**Comment by Chaser324** [comment]
*the responsible dev has logged on*

Good idea, but I would prefer to do this as an optional utility in the [Unity Build Actions](https://github.com/Chaser324/unity-build-actions) repo.

**Comment by Chaser324** [comment]
Migrated to https://github.com/Chaser324/unity-build-actions/issues/9
