### ISSUE TITLE
Enhancement: Change VR/XR Player Settings based on Distribution

### ISSUE THREAD

**Issue by russellweed** [Chaser324/unity-build#30]
Along the same lines as Issue #6 and #27, it would be great if you could also set VR/XR Player settings according to the existing Filter system.

For example, we could re-arrange the preferred SDK order based on the distribution platform, or even leave  them all out except for "None" for a non-VR build.

**Comment by robinnorth** [comment]
This is a feature I've found myself needing for a project I'm currently working on. I have implemented a build action that allows you to update XR settings on a per-Release Type basis: https://github.com/Chaser324/unity-build-actions/pull/13

**Comment by Chaser324** [comment]
@robinnorth Thanks! Great contribution. Quite a few good pull requests lately that I need to get merged. I've been on the road for work for the past couple of weeks, but I will get this merged as soon as possible.

**Comment by russellweed** [comment]
@robinnorth This is perfect, thank you!
