### ISSUE TITLE
Unity PostProcessBuild not firing 

### ISSUE THREAD

**Issue by mikest34** [Chaser324/unity-build#33]
Hi, 
Interesting alternative to UCB for those with a lot of Build targets, but I am running into one issue. The PostProcessBuild attribute methods are not being called for each platform after the build completes in 2017.3

Not sure if I am missing something.

thanks!

**Comment by Chaser324** [comment]
Any chance this could be tied to #32? Does removing and re-adding those post-build actions cause them to start working again?

**Comment by Chaser324** [comment]
Ah. I see. You're correct that those defines are only applied to the build
output and not during the build. Making that work would probably involve
some fundamental changes to the way the entire system works.

The intended way to get per-build processing like that with SuperUnityBuild
is with BuildActions. Please consult the wiki for more info:
https://github.com/Chaser324/unity-build/wiki/Build-Actions

**Comment by mikest34** [comment]
OK thanks for the response. I already started converting the scripts I am using over to BuildActions as I assumed this might be your response :)

Can you confirm that code in the build will work as expected with the correct compiler define? So my achievements code that executes will be the Steam vs GOG? I've not run any tests on that yet but will check it out tomorrow.

thanks for the tool and the support btw. top notch!

**Comment by konsnos** [comment]
I'm having a similar issue. My post-process script depends on the custom define to modify the XCode project and they don't work with SuperUnityBuild. What would be the best way to proceed with it?
