### ISSUE TITLE
Building wipes out scripting define symbols

### ISSUE THREAD

**Issue by wilg** [Chaser324/unity-build#36]
I have multiple assets (like the post processing stack) that set scripting define symbols in `ProjectSettings/ProjectSettings.asset`. 

Building with this tool always wipes them out. It would be nice if it could just add its own symbols to the list rather than replacing them. I can't really move the symbols into SuperUnityBuild because the assets themselves automatically define these symbols. Many assets seem to do it so it is apparently a common pattern.

This issue is also described here: https://github.com/Chaser324/unity-build/issues/12#issuecomment-293744300

Here's my git diff after running a build:

```diff
--- a/ProjectSettings/ProjectSettings.asset
+++ b/ProjectSettings/ProjectSettings.asset
@@ -118,7 +118,7 @@ PlayerSettings:
     16:10: 1
     16:9: 1
     Others: 1
-  bundleVersion: 1010
+  bundleVersion: 1011
   preloadedAssets: []
   metroInputSource: 0
   wsaTransparentSwapchain: 0
@@ -553,7 +553,7 @@ PlayerSettings:
   webGLCompressionFormat: 1
   webGLLinkerTarget: 1
   scriptingDefineSymbols:
-    1: DOTWEEN_TMP;DOTWEEN_TMP;UNITY_POST_PROCESSING_STACK_V2;FIRST_PERSON_CONTROLLER;THIRD_PERSON_CONTROLLER;ULTIMATE_CHARACTER_CONTROLLER_SHOOTER;ULTIMATE_CHARACTER_CONTROLLER_MELEE;AMPLIFY_SHADER_EDITOR;GPU_INSTANCER
+    1: BUILD_TYPE_PRIMARY;BUILD_PLATFORM_PC;BUILD_ARCH_WINDOWSX64
     4: DOTWEEN_TMP
     7: UNITY_POST_PROCESSING_STACK_V1;DOTWEEN_TMP;UNITY_POST_PROCESSING_STACK_V2
     13: UNITY_POST_PROCESSING_STACK_V1;DOTWEEN_TMP;UNITY_POST_PROCESSING_STACK_V2
```

**Comment by Chaser324** [comment]
Ah. I hadn't really accounted for this. #12 is a slightly more specific scenario that I already addressed, but I really should've adopted a more general approach that would've fixed this issue as well.

I should be able to get a fix out for this within the next day or two.

**Comment by wilg** [comment]
Wow, great! Thanks!

**Comment by Chaser324** [comment]
This should now be fixed. Let me know if there's a scenario that this change doesn't address.

**Comment by robinnorth** [comment]
FWIW, can confirm this has been working just fine for me in builds I have been producing using Super Unity Build (including ones that set custom defines as part of a release) since this commit, so you could consider closing this issue.
