### ISSUE TITLE
After upgrading to Unity 2018, releaseType.sceneList no longer has a "GetSceneList()" function

### ISSUE THREAD

**Issue by pearcemichal** [Chaser324/unity-build#40]
On this line:

string error = BuildPipeline.BuildPlayer(**releaseType.sceneList.GetSceneList(),** Path.Combine(buildPath, exeName), architecture.target, options);

SceneList does not have a "GetSceneList()" function

Is there any alternative way to get the information that BuildPlayer needs to run?

**Comment by Chaser324** [comment]
It looks like you're using an older release because there's no reference to that `GetSceneList()` method in the current code.

Currently, the portion of BuildProject.cs that you're referencing looks like this:

```cs
#if UNITY_2018_1_OR_NEWER
        UnityEditor.Build.Reporting.BuildReport buildReport = BuildPipeline.BuildPlayer(releaseType.sceneList.GetSceneFileList(), Path.Combine(buildPath, exeName), architecture.target, options);
        if (buildReport.summary.result == UnityEditor.Build.Reporting.BuildResult.Failed)
            error = buildReport.summary.totalErrors + " occurred.";
#else
        error = BuildPipeline.BuildPlayer(releaseType.sceneList.GetSceneFileList(), Path.Combine(buildPath, exeName), architecture.target, options);
#endif
```
