### ISSUE TITLE
Spacing issue with Unity's new UI in 2019.3x

### ISSUE THREAD

**Issue by cr4yz** [Chaser324/unity-build#43]
https://crayz.tv/files/sharex/Unity_2019-06-01_18-30-22.png

https://github.com/Chaser324/unity-build/blob/e600119a8449bfe4e72f9540bb6986ca8a9e46f9/Editor/Build/UI/UnityBuildGUIUtility.cs#L66

Setting the above line to GUI.skin.textArea solves the problem.

**Comment by Mrgove10** [comment]
👍 omg thank you **So** much do you plan to make a pull request  to change it ?
