### ISSUE TITLE
Warning 'BuildTarget.StandaloneLinux' is obsolete - 2019.2+

### ISSUE THREAD

**Issue by jasonleekennedy** [Chaser324/unity-build#45]
I get the following warnings on 2019.3 (went to the beta because of a SSAO rendering bug.. first version I could find without it)
I also get a few other errors (LInux build seems to work for me)
```
Assets/unity-build/Editor/Build/Platform/BuildLinux.cs(33,39): warning CS0618: 'BuildTarget.StandaloneLinux' is obsolete: 'StandaloneLinux has been removed in 2019.2'
```
```
Assets/unity-build/Editor/Build/Platform/BuildLinux.cs(32,39): warning CS0618: 'BuildTarget.StandaloneLinuxUniversal' is obsolete: 'StandaloneLinuxUniversal has been removed in 2019.2'
```

**Comment by Chaser324** [comment]
Yeah, it looks like I need to update the build architectures for these newer 2019 releases of Unity. Should be a quick fix.

**Comment by hedgefield** [comment]
Looking forward to 2019 compatibility!
