### ISSUE TITLE
Can't add any pre/post actions

### ISSUE THREAD

**Issue by TupiNUMBooR** [Chaser324/unity-build#46]
I don't see any buttons to add actions.
Linux, Unity 2018.4

![image](https://user-images.githubusercontent.com/19345649/65482613-52fea880-dea2-11e9-939a-74e16eb80550.png)

**Comment by robinnorth** [comment]
Might be a dumb question, but have you added some/all of the build actions (https://github.com/Chaser324/unity-build-actions) to your project?

**Comment by TupiNUMBooR** [comment]
Oops, i didn't realize they are placed in other project. Thanks!
