### ISSUE TITLE
Build actions are not being called.

### ISSUE THREAD

**Issue by the-mr-matt** [Chaser324/unity-build#48]
I have created 2 build actions, one post and one pre build. The first updates the description in the steam app vdf file with the version number of the build. The second executes the batch file that uploads the build to the steam depots.

I tried adding a `Debug.Log()` to the execute method and only the post build gets called, however the rest of the code does not seem to execute.

```
public class SteamAppVersionNumber : BuildAction, IPreBuildAction
{
    private const string FILE_PATH_WINDOWS = @"C:\Unity Data\steamworks_sdk_142\sdk\tools\ContentBuilder\scripts\app_build_<my app build number>_rr.vdf";

    public override void Execute()
    {
        Debug.Log("EXECUTE VERSION NUMBER");
            
        // Update the version number in the Steam app .vdf file prior to building.
        string content = File.ReadAllText(FILE_PATH_WINDOWS);
        string pattern = @"""desc"" "".*""";
        string replacement = $@"""desc"" ""{UnityEngine.Application.version}""";
        content = Regex.Replace(content, pattern, replacement);

        File.WriteAllText(FILE_PATH_WINDOWS, content);
    }
}
```

```
public class SteamBuildUpload : BuildAction, IPostBuildAction
{
    private const string FILE_PATH_WINDOWS = @"C:\Unity Data\steamworks_sdk_142\sdk\tools\ContentBuilder\run_build_radical_relocation.bat";

    public override void Execute()
    {
        UnityEngine.Debug.Log("EXECUTE STEAM UPLOAD");

        Process.Start(FILE_PATH_WINDOWS);
    }
}
```

**Comment by the-mr-matt** [comment]
I found a work around. Adding a filter to the build actions, and then deleting the filter seemed to work. I wonder if there was a filter by default that wasn't drawing in the inspector. If so, it would be blank and wouldn't match the conditions, hence it wouldn't run. Just speculation though.

**Comment by robinnorth** [comment]
@the-mr-matt did this only happen in one particular project for you, or consistently?

**Comment by the-mr-matt** [comment]
I believe this is resolved now, I've added build actions since then with no issue.

**Comment by robinnorth** [comment]
Thanks for confirming, @the-mr-matt!
