### ISSUE TITLE
Complete Android, iOS, WebGL BuildPlatforms.

### ISSUE THREAD

**Issue by Chaser324** [Chaser324/unity-build#7]
- [x] Android
- [x] WebGL
- [ ] iOS

**Comment by Chaser324** [comment]
@zulfajuniadi There's already an itch.io uploader available in the extensions repo: https://github.com/Chaser324/unity-build-actions

**Comment by ertugrul013** [comment]
When can we expect a release for the . unity package

**Comment by MostHated** [comment]
By the looks of this, never

**Comment by Chaser324** [comment]
https://github.com/Chaser324/unity-build/releases/tag/v0.9.8

**Comment by MostHated** [comment]
Well, I'll be darned.

**Comment by chloethompson** [comment]
Wondering when there will a release for the iOS build/ if there will be one?

**Comment by Chaser324** [comment]
@chloethompson Thanks for taking a look the iOS build functionality. I've wanted to integrate that for a long time. I don't have a Mac though, so I have no means of actually testing it to see if it's working properly.

I'll get your pull request integrated into a new release later this week.

**Comment by chloethompson** [comment]
Thanks @robinnorth for testing that to make sure!

**Comment by kcajf** [comment]
Is there anything blocking your PR @chloethompson ? iOS builds would be super useful!
